spring:
  application:
    name: purchase
  datasource:
    url: jdbc:mysql://localhost:3306/purchase
    username: sagaz
    password: havasagaz
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 5672
    username: sagaz
    password: secret

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8001